Core_Prac_01/Controllers/ApplicantsController.cs
using Core_Prac_01.Models;
using Core_Prac_01.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace Core_Prac_01.Controllers
{
    public class ApplicantsController : Controller
    {
        private readonly ApplicantDbContext db;
        private readonly IWebHostEnvironment env;
        public ApplicantsController(ApplicantDbContext db, IWebHostEnvironment env)
        {
            this.db = db;
            this.env = env;
        }

        public async Task<IActionResult> Index(int pg = 1)
        {
            var data = await db.Applicants.Include(a => a.Qualifications).ToPagedListAsync(pg, 5);
            return View(data);
        }
        public IActionResult Create()
        {
            var model = new ApplicantInputModel();
            model.Qualifications.Add(new QualificationInputModel());
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Create(ApplicantInputModel model, string act = "")
        {
            if (act == "add")
            {
                model.Qualifications.Add(new QualificationInputModel());
            }
            if (act.StartsWith("remove"))
            {

                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Qualifications.RemoveAt(index);
            }
            if (act == "insert")
            {
                if (ModelState.IsValid)
                {
                    Applicant a = new Applicant
                    {
                        ApplicantName = model.ApplicantName,
                        Gender = model.Gender,
                        AppliedFor = model.AppliedFor,
                        BirthDate = model.BirthDate,
                        IsReadyToWorkAnyWhere = model.IsReadyToWorkAnyWhere
                    };
                    string ext = Path.GetExtension(model.Picture.FileName);
                    string fn = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string sp = Path.Combine(env.WebRootPath, "Pictures", fn);
                    FileStream fs = new FileStream(sp, FileMode.Create);
                    await model.Picture.CopyToAsync(fs);
                    fs.Close();
                    a.Picture = fn;
                    foreach (var x in model.Qualifications)
                    {
                        a.Qualifications.Add(new Qualification { Degree = x.Degree, Institute = x.Institute, PassingYear = x.PassingYear, Result = x.Result });
                    }
                    await db.Applicants.AddAsync(a);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var a = await db.Applicants.Include(x => x.Qualifications).FirstOrDefaultAsync(x => x.ApplicantId == id);
            if (a == null) { return NotFound(); }
            var model = new ApplicantEditModel
            {
                ApplicantId = a.ApplicantId,
                ApplicantName = a.ApplicantName,
                AppliedFor = a.AppliedFor,
                BirthDate = a.BirthDate,
                Gender = a.Gender,
                IsReadyToWorkAnyWhere = a.IsReadyToWorkAnyWhere,

            };
            foreach (var x in a.Qualifications)
            {
                model.Qualifications.Add(new QualificationInputModel
                {
                    QualificationId = x.QualificationId,
                    Degree = x.Degree,
                    Institute = x.Institute,
                    PassingYear = x.PassingYear,
                    Result = x.Result
                });
            }
            ViewBag.CurrentPic = a.Picture;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ApplicantEditModel model, string act = "")
        {
            if (act == "add")
            {
                model.Qualifications.Add(new QualificationInputModel());
            }
            if (act.StartsWith("remove"))
            {

                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Qualifications.RemoveAt(index);
            }
            if (act == "update")
            {
                if (ModelState.IsValid)
                {
                    var a = await db.Applicants.Include(x => x.Qualifications).FirstOrDefaultAsync(x => x.ApplicantId == model.ApplicantId);
                    if (a == null) { return NotFound(); }
                    a.ApplicantName = model.ApplicantName;
                    a.AppliedFor = model.AppliedFor;
                    a.BirthDate = model.BirthDate;
                    a.Gender = model.Gender;
                    a.IsReadyToWorkAnyWhere = model.IsReadyToWorkAnyWhere;
                    if (model.Picture != null)
                    {
                        string ext = Path.GetExtension(model.Picture.FileName);
                        string fn = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string sp = Path.Combine(env.WebRootPath, "Pictures", fn);
                        FileStream fs = new FileStream(sp, FileMode.Create);
                        await model.Picture.CopyToAsync(fs);
                        fs.Close();
                        a.Picture = fn;
                    }
                    db.Qualifications.RemoveRange(a.Qualifications.ToList());
                    foreach (var x in model.Qualifications)
                    {
                        a.Qualifications.Add(new Qualification { Degree = x.Degree, Institute = x.Institute, PassingYear = x.PassingYear, Result = x.Result });
                    }

                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var a = await db.Applicants.Include(x => x.Qualifications).FirstOrDefaultAsync(x => x.ApplicantId == id);
            return View(a);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DoDelete(int id)
        {
            var a = await db.Applicants.Include(x => x.Qualifications).FirstOrDefaultAsync(x => x.ApplicantId == id);
            if (a == null) { return NotFound(); }
            db.Applicants.Remove(a);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        //
        // Qualifactions
        ////////////////////////////////////////////
        //
        public IActionResult CreateQualification(int applicantId)
        {
            ViewBag.Applicants = db.Applicants.Select(x => new { x.ApplicantId, x.ApplicantName }).ToList();
            ViewBag.ApplicantId = applicantId;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateQualification(QualificationInputModel model)
        {
            if (ModelState.IsValid)
            {
                await db.Qualifications.AddAsync(new Qualification { Degree = model.Degree, Institute = model.Institute, PassingYear = model.PassingYear, Result = model.Result, ApplicantId = model.ApplicantId });
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Applicants = db.Applicants.Select(x => new { x.ApplicantId, x.ApplicantName }).ToList();
            ViewBag.ApplicantId = model.ApplicantId;
            return View(model);
        }
        public async Task<IActionResult> EditQualification(int id)
        {
            var q = await db.Qualifications.FirstOrDefaultAsync(x => x.QualificationId == id);
            if (q == null) return NotFound();
            ViewBag.Applicants = db.Applicants.Select(x => new { x.ApplicantId, x.ApplicantName }).ToList();

            return View(new QualificationInputModel
            {
                QualificationId = q.QualificationId,
                ApplicantId = q.ApplicantId,
                Degree = q.Degree,
                Institute = q.Institute,
                PassingYear = q.PassingYear,
                Result = q.Result,
            });
        }
        [HttpPost]
        public async Task<IActionResult> EditQualification(QualificationInputModel model)
        {
            var q = await db.Qualifications.FirstOrDefaultAsync(x => x.QualificationId == model.QualificationId);
            if (q == null) return NotFound();
            if (ModelState.IsValid)
            {
                q.ApplicantId = model.ApplicantId;
                q.Degree = model.Degree;
                q.PassingYear = model.PassingYear;
                q.Institute = model.Institute;
                q.Result = model.Result;

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Applicants = db.Applicants.Select(x => new { x.ApplicantId, x.ApplicantName }).ToList();

            return View(model);
        }
        public async Task<IActionResult> DeleteQualification(int id)
        {
            var a = await db.Qualifications.Include(x => x.Applicant).FirstOrDefaultAsync(x => x.QualificationId == id);


            return View(a);
        }
        [HttpPost, ActionName("DeleteQualification")]
        public async Task<IActionResult> DoDeleteQualification(int id)
        {
            var a = await db.Qualifications.Include(x => x.Applicant).FirstOrDefaultAsync(x => x.QualificationId == id);
            if (a == null) { return NotFound(); }
            db.Qualifications.Remove(a);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Core_Prac_01/Views/Applicants/CreateQualification.cshtml
@model QualificationInputModel
@{
    ViewData["Title"] = "CreateQualification";
}
<div class="row">
    <div class="col-12">

        <form asp-action="CreateQualification" asp-controller="Applicants" method="post">
            <h3>Add new qualication</h3>
            <div class="form-group row mb-1">
                <label asp-for="ApplicantId" class="col-form-label col-form-label-sm col-3 text-end"></label>
                <div class="col-4">
                    <select class="form-select form-select-sm " asp-for="ApplicantId" asp-items="@(new SelectList(ViewBag.Applicants, "ApplicantId", "ApplicantName", ViewBag.ApplicantId))">
                    </select>
                    <span asp-validation-for="ApplicantId" class="text-danger" style="font-size:small"></span>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="form-group row mb-1">
                    <label asp-for="Degree" class="col-form-label col-form-label-sm col-3 text-end"></label>
                    <div class="col-4">
                        <input asp-for="Degree" class="form-control form-control-sm" />
                        <span asp-validation-for="Degree" class="text-danger" style="font-size:small"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="form-group row mb-1">
                    <label asp-for="Institute" class="col-form-label col-form-label-sm col-3 text-end"></label>
                    <div class="col-4">
                        <input asp-for="Institute" class="form-control form-control-sm" />
                        <span asp-validation-for="Institute" class="text-danger" style="font-size:small"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="form-group row mb-1">
                    <label asp-for="PassingYear" class="col-form-label col-form-label-sm col-3 text-end"></label>
                    <div class="col-4">
                        <input asp-for="PassingYear" class="form-control form-control-sm" />
                        <span asp-validation-for="PassingYear" class="text-danger" style="font-size:small"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="form-group row mb-1">
                    <label asp-for="Result" class="col-form-label col-form-label-sm col-3 text-end"></label>
                    <div class="col-4">
                        <input asp-for="Result" class="form-control form-control-sm" />
                        <span asp-validation-for="Result" class="text-danger" style="font-size:small"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-8">
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section scripts
{
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/validate/jquery.validate.js"></script>
    <script src="~/libs/unobtrusive/jquery.validate.unobtrusive.js"></script>
}

Core_Prac_01/Views/Applicants/DeleteQualification.cshtml
@model Qualification
@{
    ViewData["Title"] = "DeleteQualification";
}

<div class="row">
    <div class="col-12">
        <div class="form-group row mb-1">
            <label asp-for="ApplicantId" class="col-form-label col-form-label-sm col-2 text-end"></label>
            <div class="col-6">
                @Model.Applicant.ApplicantName
            </div>
        </div>
        <div class="form-group row mb-1">
            <label asp-for="Degree" class="col-form-label col-form-label-sm col-2 text-end"></label>
            <div class="col-6">
                @Model.Degree

            </div>
        </div>
        <div class="form-group row mb-1">
            <label asp-for="Institute" class="col-form-label col-form-label-sm col-2 text-end"></label>
            <div class="col-6">
                @Model.Institute

            </div>
        </div>
        <div class="form-group row mb-1">
            <label asp-for="PassingYear" class="col-form-label col-form-label-sm col-2 text-end"></label>
            <div class="col-6">
                @Model.PassingYear

            </div>
        </div>
        <div class="form-group row mb-1">
            <label asp-for="Result" class="col-form-label col-form-label-sm col-2 text-end"></label>
            <div class="col-6">
                @Model.Result

            </div>
        </div>
        <div class="form-group row mb-1">
            <div class="col-8">
                <form asp-action="Delete" asp-controller="Applicants" asp-route-id="@Model.QualificationId" method="post">

                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-danger" name="act" value="insert">Confirm Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Core_Prac_01/Views/Applicants/Edit.cshtml
@model ApplicantEditModel
@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-12">
        <form asp-action="Edit" asp-controller="Applicants" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="ApplicantId" />
            <div class="form-group row mb-1">
                <label asp-for="ApplicantName" class="col-form-label col-form-label-sm col-2 text-end"></label>
                <div class="col-6">
                    <input type="text" asp-for="ApplicantName" class="form-control form-control-sm" />
                    <span asp-validation-for="ApplicantName" class="text-danger" style="font-size:small" />
                </div>
            </div>
            <div class="form-group row mb-1">
                <label asp-for="AppliedFor" class="col-form-label col-form-label-sm col-2 text-end"></label>
                <div class="col-6">
                    <select asp-for="AppliedFor" class="form-select form-select-sm">
                        <option>Sales exective</option>
                        <option>Area manager</option>
                        <option>Zone manager</option>
                        <option>Promotion officer</option>
                    </select>
                    <span asp-validation-for="AppliedFor" class="text-danger" style="font-size:small" />
                </div>
            </div>
            <div class="form-group row mb-1">
                <label asp-for="BirthDate" class="col-form-label col-form-label-sm col-2 text-end"></label>
                <div class="col-6">
                    <input type="text" asp-for="BirthDate" class="form-control form-control-sm" />
                    <span asp-validation-for="BirthDate" class="text-danger" style="font-size:small" />
                </div>
            </div>
            <div class="form-group row mb-1">
                <label asp-for="Gender" class="col-form-label col-form-label-sm col-2 text-end"></label>
                <div class="col-6">
                    <select type="text" asp-for="Gender" class="form-select form-select-sm"
                            asp-items="Html.GetEnumSelectList<Gender>()">
                        <option value="" selected>Choose one</option>
                    </select>
                    <span asp-validation-for="Gender" class="text-danger" style="font-size:small" />
                </div>
            </div>
            <div class="form-group row mb-1">
                <label asp-for="Picture" class="col-form-label col-form-label-sm col-2 text-end"></label>
                <div class="col-6">
                    <input type="file" asp-for="Picture" class="form-control form-control-sm" />
                    <span asp-validation-for="Picture" class="text-danger" style="font-size:small" />
                </div>
            </div>
            <div class="form-group row mb-1">

                <div class="col-6 offset-2">
                    <div class="form-check">
                        <input type="checkbox" asp-for="IsReadyToWorkAnyWhere">
                        <label class="form-check-label" for="flexCheckDefault">
                            Ready to work anywhere in country
                        </label>
                    </div>
                    <span asp-validation-for="IsReadyToWorkAnyWhere" class="text-danger" style="font-size:small" />
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-8">
                    <h4>Qualifications</h4>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Degree</th>
                                <th>Institute</th>
                                <th>Passing Year</th>
                                <th>Result</th>
                                <th>
                                    <button type="submit" formnovalidate name="act" value="add" class="btn btn-sm btn-secondary">Add</button>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (var i = 0; i < Model.Qualifications.Count; i++)
                            {
                                <tr>
                                    <td>
                                        <input asp-for="@Model.Qualifications[i].Degree" class="form-control form-control-sm" />
                                        <span asp-validation-for="@Model.Qualifications[i].Degree" class="text-danger" style="font-size:small" />
                                    </td>
                                    <td>
                                        <input asp-for="@Model.Qualifications[i].Institute" class="form-control form-control-sm" />
                                        <span asp-validation-for="@Model.Qualifications[i].Institute" class="text-danger" style="font-size:small" />
                                    </td>
                                    <td>
                                        <input asp-for="@Model.Qualifications[i].PassingYear" class="form-control form-control-sm" />
                                        <span asp-validation-for="@Model.Qualifications[i].PassingYear" class="text-danger" style="font-size:small" />
                                    </td>
                                    <td>
                                        <input asp-for="@Model.Qualifications[i].Result" class="form-control form-control-sm" />
                                        <span asp-validation-for="@Model.Qualifications[i].Result" class="text-danger" style="font-size:small" />
                                    </td>
                                    <td>
                                        <button type="submit" class="btn btn-danger btn-sm" formnovalidate name="act" value="remove_@i">Del</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-8">
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary" name="act" value="update">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section styles
{
    <link href="~/libs/datepicker/css/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts
{
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/validate/jquery.validate.js"></script>
    <script src="~/libs/unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/libs/datepicker/js/bootstrap-datepicker.js"></script>
    <script>
        $("#BirthDate").datepicker({
            format: 'yyyy-mm-dd'
        });
        $("#BirthDate").val(formatDate($("#BirthDate").val()));
        function formatDate(dt) {
            var d = new Date(dt);
            return [
                d.getFullYear(),
                (d.getMonth() + 1).toString().padStart(2, '0'),
                d.getDate().toString().padStart(2, '0')
            ].join('-');
        }
    </script>
}

Core_Prac_01/Views/Applicants/EditQualification.cshtml
@model QualificationInputModel
@{
    ViewData["Title"] = "EditQualification";
}
<div class="row">
    <div class="col-12">
        <form asp-action="EditQualification" asp-controller="Applicants" method="post">
            <h3>Edit qualication</h3>
            <input type="hidden" asp-for="QualificationId" />
            <div class="form-group row mb-1">
                <label asp-for="ApplicantId" class="col-form-label col-form-label-sm col-3 text-end"></label>
                <div class="col-4">
                    <select class="form-select form-select-sm " asp-for="ApplicantId" asp-items="@(new SelectList(ViewBag.Applicants, "ApplicantId", "ApplicantName"))">
                    </select>
                    <span asp-validation-for="ApplicantId" class="text-danger" style="font-size:small"></span>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="form-group row mb-1">
                    <label asp-for="Degree" class="col-form-label col-form-label-sm col-3 text-end"></label>
                    <div class="col-4">
                        <input asp-for="Degree" class="form-control form-control-sm" />
                        <span asp-validation-for="Degree" class="text-danger" style="font-size:small"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="form-group row mb-1">
                    <label asp-for="Institute" class="col-form-label col-form-label-sm col-3 text-end"></label>
                    <div class="col-4">
                        <input asp-for="Institute" class="form-control form-control-sm" />
                        <span asp-validation-for="Institute" class="text-danger" style="font-size:small"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="form-group row mb-1">
                    <label asp-for="PassingYear" class="col-form-label col-form-label-sm col-3 text-end"></label>
                    <div class="col-4">
                        <input asp-for="PassingYear" class="form-control form-control-sm" />
                        <span asp-validation-for="PassingYear" class="text-danger" style="font-size:small"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="form-group row mb-1">
                    <label asp-for="Result" class="col-form-label col-form-label-sm col-3 text-end"></label>
                    <div class="col-4">
                        <input asp-for="Result" class="form-control form-control-sm" />
                        <span asp-validation-for="Result" class="text-danger" style="font-size:small"></span>
                    </div>
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-8">
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section scripts
{
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/validate/jquery.validate.js"></script>
    <script src="~/libs/unobtrusive/jquery.validate.unobtrusive.js"></script>
}

Core_Prac_01/Views/Applicants/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@model IEnumerable<Applicant>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-12">
        <h3>Employee List</h3>
        <div class="d-flex justify-content-end mb-1">
            <a href="@Url.Action("Create", "Applicants")" class="btn btn-primary btn-sm">Create New</a>
        </div>
        <table class="table table-bordered table-striped">
            <thead class="table-light">
                <tr>
                    <th></th>
                    <th></th>
                    <th>Applicant Name</th>
                    <th>Gender</th>
                    <th>Birth Date</th>
                    <th>Applied For</th>
                    <th>Ready to work anywhere?</th>
                    <th>...</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var a in Model)
                {
                    <tr style="vertical-align:middle">

                        <td>
                            <button class="btn show"><i class="bi bi-caret-right"></i></button>
                            <button class="btn hide" style="display:none"><i class="bi bi-caret-up"></i></button>
                        </td>

                        <td><img src="~/Pictures/@a.Picture" class="img-thumbnail rounded-circle" style="width:50px" /></td>
                        <td>@a.ApplicantName</td>
                        <td>@a.Gender</td>
                        <td>@a.BirthDate.ToString("yyyy-MM-dd")</td>
                        <td>@a.AppliedFor</td>
                        <td>@(a.IsReadyToWorkAnyWhere ? "Yes" : "No")</td>
                        <td>
                            <a asp-action="Edit" asp-controller="Applicants" asp-route-id="@a.ApplicantId" class="btn btn-success btn-sm">Edit</a>
                            <a asp-action="Delete" asp-controller="Applicants" asp-route-id="@a.ApplicantId" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                    <tr style="display:none">
                        <td></td>
                        <td colspan="5">
                            <h4>Qualifications</h4>
                            <div class="d-flex justify-content-end mb-1">
                                <a asp-controller="Applicants" asp-action="CreateQualification" asp-route-applicantId="@a.ApplicantId" class="btn btn-primary btn-sm">Create New</a>
                            </div>
                            <table class="table table-bordered">
                                <thead class="table-light">
                                    <tr>
                                        <th>Degree</th>
                                        <th>Institute</th>
                                        <th>Passing year</th>
                                        <th>Result</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var q in a.Qualifications)
                                    {
                                        <tr>
                                            <td>@q.Degree</td>
                                            <td>@q.Institute</td>
                                            <td>@q.PassingYear</td>
                                            <td>@q.Result</td>
                                            <td>
                                                <a class="btn btn-primary btn-sm" asp-action="EditQualification" asp-route-id="@q.QualificationId" asp-controller="Applicants">Edit</a>
                                                <a class="btn btn-danger btn-sm" asp-action="DeleteQualification" asp-route-id="@q.QualificationId" asp-controller="Applicants">Delete</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="d-flex justify-content-end">
            @Html.PagedListPager((IPagedList)Model, pg => Url.Action("Index", new { pg }), new PagedListRenderOptions
       {
           LiElementClasses = new string[] { "page-item" },
           PageClasses = new string[] { "page-link" },
           DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
           DisplayLinkToNextPage = PagedListDisplayMode.Always
       })

        </div>
    </div>
</div>
@section styles
{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
}
@section scripts
{
    <script src="~/libs/jquery/jquery.js"></script>
    <script>
        $(".show").click(function () {
            $(this).hide();
            $(this).next().show();
            $(this).closest("tr").next().show();
        });
        $(".hide").click(function () {
            $(this).hide();
            $(this).prev().show();
            $(this).closest("tr").next().hide();
        });
    </script>
}